# fly.toml app configuration file generated for test-s7to2w on 2025-07-05T22:10:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-s7to2w'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
